<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DashboardService.Domain\DashboardService.Domain.csproj" />
    <ProjectReference Include="..\DashboardService.Infrastructure\DashboardService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
