apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-postgres-pvc
  namespace: service-health-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
