apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres
  namespace: service-health-dashboard
spec:
  type: ClusterIP
  selector:
    app: inventory-postgres
  ports:
    - port: 5432
      targetPort: 5432
